# Default values for mirrored-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

autoscaling:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  registry:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  storage:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  # ingress class to assign
  # defaults to nginx if not specified
  className: ""
  baseHostName: registry.homelabs.io
  certmanager:
    enabled: true
    # cluster-issuer or issuer
    # defaults to namespace-scoped issuer
    issuerType: ""
    issuerName: "letsencrypt-production"

storage:
  # type: filesystem, s3 [in-cluster minio],
  # type: "filesystem"
  type: "s3"
  s3:
    # enabled: true
    rootAccessKey:
    rootSecretKey:
    region: us-east-1
    # regionEndpoint:
    # bucket:
    v4Auth: true
    # replicaCount: 3
    mode: standalone # distributed
    replicaSize: 20Gi
cache:
  enabled: true

registries:
  - name: docker-io
    enabled: true
    replicaCount: 3
    autoscaling:
      enabled: true
    cache:
      enabled: false
    image:
      tag: ""
    storage:
      size: 7Gi
    upstreamURL: "https://registry-1.docker.io"
  - name: k8s-gcr-io
    enabled: false
    replicaCount: 2
    autoscaling:
      enabled: false
    cache:
      enabled: true
    image:
      tag: ""
    storage:
      size: 5Gi
    upstreamURL: "https://k8s.gcr.io"
  - name: gcr-io
    enabled: false
    replicaCount: 1
    autoscaling:
      enabled: false
    cache:
      enabled: true
    image:
      tag: ""
    storage:
      size: 5Gi
    upstreamURL: "https://gcr.io"
  - name: ghcr-io
    enabled: false
    replicaCount: 1
    autoscaling:
      enabled: false
    cache:
      enabled: true
    image:
      tag: ""
    storage:
      size: 5Gi
    upstreamURL: "https://ghcr.io"
  - name: quay-io
    enabled: false
    replicaCount: 1
    autoscaling:
      enabled: false
    cache:
      enabled: true
    image:
      tag: "2.5"
    storage:
      size: "5Gi"
    upstreamURL: "https://quay.io"

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
