{{- $dot := . }}
{{- range .Values.registries }}
{{- if and .enabled .cache.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-{{ .name }}-config
  namespace: {{ $dot.Release.Namespace }}
  labels:
    app: cache
    registry: {{ .name }}
data:
  master.conf: |
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    appendonly no
    dbfilename dump.rdb
    dir /data
  slave.conf: |
    slaveof redis-ss-0.redis-ss.redis 6379
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    dir /data
{{- end }}
{{- end }}
