{{- $dot := . }}
{{- range .Values.registries }}
{{- if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-registry- # todo: finish
  namespace: registry
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - registry- # todo: finish
      secretName: registry-production-certificate
  rules:
    - host: registry- # todo: finish
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry- #todo: finish
                port:
                  number: 5000

{{- end }}
{{- end }}
