{{- $dot := . }}
{{- range .Values.registries }}
{{- if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ include "mirrored-registry.name" $dot }}-{{ .name }}
  namespace: registry
  annotations:
    kubernetes.io/ingress.class: {{ $dot.Values.ingress.className | default "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if $dot.Values.ingress.certmanager.enabled}}
    cert-manager.io/{{ $dot.Values.ingress.certmanager.issuerType | default "issuer" }}: {{ $dot.Values.ingress.certmanager.issuerName }}
    {{- end}}
spec:
  tls:
    - hosts:
        - {{ .name }}.{{ $dot.Values.ingress.baseHostName }}
      secretName: tls-{{ include "mirrored-registry.name" $dot }}-{{ .name }}
  rules:
    - host: {{ .name }}.{{ $dot.Values.ingress.baseHostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mirrored-registry.name" $dot }}-{{ .name }}
                port:
                  number: 5000

{{- end }}
{{- end }}
